# Assignment(find the second highest value)
num_5 = input("Enter five numbers: ")
num_5_list = num_5.split(" ")
# print(num_5_list)
num_5_list[0] = int(num_5_list[0])
num_5_list[1] = int(num_5_list[1])
num_5_list[2] = int(num_5_list[2])
num_5_list[3] = int(num_5_list[3])
num_5_list[4] = int(num_5_list[4])
# print(num_5_list)
# first_max = max(num_5_list)
# num_5_list.remove(first_max)
# sec_max = max(num_5_list)
# print(f"The second largest number is {sec_max}")
num_5_list.sort()
print(f"The second largest number is {num_5_list[-2]}")